/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Job.JobMain;

/**
 *
 * @author J.M Vikum Chathuranga 
 *         IT13131098
 *
 */

import Class.Job.Select.JobSelect;

import java.util.Vector;
import java.util.StringTokenizer;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JobTable extends javax.swing.JPanel {

    /**
     * Creates new form JobTable
     */

    DefaultTableModel dtm;
    
    private JobSelect js;

    public JobTable() {
        initComponents();
        
        js = new JobSelect();
        
        dtm = (DefaultTableModel) tjob.getModel();
        
        loadTable();

        //this for error checking.
        System.out.println("Job table loaded.");
    }
    
    /*
    *   Begining of the OOP coding
    */
    
    private String getPart(String jobid) {
        boolean inside = false;
        boolean cover = false;
        Vector<Vector<String>> vector;
        try {
            vector = js.getCoverDetail(jobid);
            if ( vector.size() != 0 ) {
                cover = true;
            } else {
                cover = false;
            }
        } catch (NullPointerException npe) {
            System.out.println("No cover for : "+jobid);
            cover = false;
        }
        try {
            vector = js.getInsideDetail(jobid);
            if ( vector.size() != 0 ) {
                inside = true;
            } else {
                inside = false;
            }
        } catch (NullPointerException npe) {
            System.out.println("No inside for : "+jobid);
            inside = false;
        }
        if (cover == true && inside == true) {
            return "Both";
        } else if (cover == true && inside == false) {
            return "Cover only";
        } else if (cover == false && inside == true) {
            return "Inside only";
        }
        return null;
    }
    
    public void loadTable(String feild, String searchkey, String start, String end) {
        Vector<Vector<String>> jobvector;
        dtm.setRowCount(0);
        try {
            jobvector = js.searchJob(feild, searchkey, start, end);
            int size = jobvector.size();
            for ( int i = 0 ; i < size ; i++) {
                Vector<String> row = new Vector<>();
                Vector<String> v = jobvector.elementAt(i);
                row.add(v.elementAt(0));            //jobid
                //row.add(v.elementAt(1));            //itemid
                row.add(v.elementAt(2));            //item name
                row.add(v.elementAt(3));            //job current step
                row.add(v.elementAt(4));            //job added date
                row.add(getPart(v.elementAt(0)));   //Show parts of job
                //row.add(v.elementAt(5));            //item qty
                row.add(getActualQty(v.elementAt(7), v.elementAt(5)));  //Show actual added qty
                row.add(v.elementAt(6));            //Total impression
                dtm.addRow(row);
            }
        } catch (NullPointerException npe) {
            System.out.println("");
        }
    }
    
    public void loadTable(String feild, String searchkey) {
        loadTable(feild, searchkey, "", "");
    }
    
    public void loadTable() {
        loadTable("", "", "", "");
    }
    
    //This for get actual quantity 
    public String getActualQty(String waste, String qty) {
        StringTokenizer st = new StringTokenizer(waste,"/");
        int aq = -1;
        try {
            int l = Integer.parseInt(st.nextToken());
            int v = Integer.parseInt(st.nextToken());
            aq = Integer.parseInt(qty) * ( l + v ) / v ;
        } catch (NumberFormatException nfe) {
            
        }
        return Integer.toString(aq);
    }
    
    /*
    *   End of OOP coding
    */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tjob = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(824, 350));
        setPreferredSize(new java.awt.Dimension(824, 350));
        setLayout(new java.awt.BorderLayout());

        tjob.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job ID", "Item Name", "Status", "Added date", "Parts", "Qty", "Total impression"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tjob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tjobMouseClicked(evt);
            }
        });
        tjob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tjobFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(tjob);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tjobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tjobMouseClicked
        
    }//GEN-LAST:event_tjobMouseClicked

    private void tjobFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tjobFocusLost
        
    }//GEN-LAST:event_tjobFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tjob;
    // End of variables declaration//GEN-END:variables
}
